version: '3'

services:
  php:
    container_name: testgreet_app_php
    build: ./.docker/php
    volumes:
      - .:/var/www
    environment:
      TZ: Asia/Tokyo

  nginx:
    image: nginx:latest
    container_name: testgreet_app_nginx
    ports:
      - 8085:80
    volumes:
      - .:/var/www
      - .docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php